CREATE TABLE IF NOT EXISTS apps
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_app PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_id    BIGINT,
    uri       VARCHAR(255)                            NOT NULL,
    ip        VARCHAR(16)                             NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_hit PRIMARY KEY (id),
    CONSTRAINT fk_hits_to_apps FOREIGN KEY (app_id) REFERENCES apps (id)
);